# application-local.yml
server:
  port: 8080

parser:
  api:
    url: http://localhost:8001

spring:
  datasource:
    riding :
      url: jdbc:mariadb://34.172.162.148:3306/riding_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver

      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 963024529670-769djp6j8pv6hn2eetaci3nveaq7f10p.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET} # 끝에 's' 제거
            scope:
              - https://www.googleapis.com/auth/fitness.nutrition.read
              - https://www.googleapis.com/auth/fitness.body.read
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # 끝에 'o' 추가

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

inbody:
  upload:
    path: /tmp/inbody/raw/

exercise:
  gif:
    path: /tmp/exercise-gifs/   # 로컬은 안 씀
    base-url: /gif/   # → /gif/CHEST_PRESS.gif (public 폴더)

anthropic:
  api-key: ${ANTHROPIC_API_KEY}

google:
  fitness:
    api-url: https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate

lotto:
  datasource:
    enabled: false

brevet:
  nas-path: ${BREVET_NAS_PATH:}

#windy:
#  api-key: ${WINDY_API_KEY}
#  api-url: https://api.windy.com/api/point-forecast/v2
#  model: gfs  # GFS 모델 (한국 커버리지 좋음)

app:
  base-url: http://localhost:5173

