# application-local.yml
server:
  port: 8080
  forward-headers-strategy: native

spring:
  datasource:
    riding:
      url: jdbc:mariadb://172.17.0.1:3306/riding_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 415261907040-90umvp9luqjtbvs5tft2jps2h126iq2h.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://ride.tho881.me/login/oauth2/code/google"
            scope:
              - https://www.googleapis.com/auth/fitness.nutrition.read
              - https://www.googleapis.com/auth/fitness.body.read
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

inbody:
  upload:
    path: /mnt/200gb/NAS/inbody/raw/

anthropic:
  api-key: ${ANTHROPIC_API_KEY}

# 파일 끝에 추가
google:
  fitness:
    api-url: https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate

brevet:
  nas-path: /data/home/tho881/project/NAS/brevet
